### ISSUE TITLE
test: add blockstore interface tests

### ISSUE THREAD

**Issue by SgtPooki** [dozyio/js-blockstore-opfs#1]
In js-stores repo, there are interface tests that run common tests to ensure blockstores are adhering to common functionality. We should add that test here.

```
import { interfaceBlockstoreTests } from 'interface-blockstore-tests'

  describe('interface-blockstore (opfs)', () => {
    interfaceBlockstoreTests({
      async setup () {
        const store = new OpfsBlockstore(`hello-${Math.random()}`)
        await store.open()
        return store
      },
      async teardown (store) {
        await store.close()
        await store.destroy()
      }
    })
  })
```

**Comment by dozyio** [comment]
Hey @SgtPooki - I'm running the current tests through playwright as OPFS is browser only with no node support so I don't think those tests will run

**Comment by dozyio** [comment]
added interfaceBlockstoreTests
